<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#numpy" data-toc-modified-id="numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>numpy</a></span><ul class="toc-item"><li><span><a href="#导入numpy库" data-toc-modified-id="导入numpy库-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>导入numpy库</a></span></li><li><span><a href="#numpy的两种数据结构之一：数组" data-toc-modified-id="numpy的两种数据结构之一：数组-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>numpy的两种数据结构之一：数组</a></span></li><li><span><a href="#numpy的两种数据结构之二：矩阵" data-toc-modified-id="numpy的两种数据结构之二：矩阵-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>numpy的两种数据结构之二：矩阵</a></span></li><li><span><a href="#矩阵运算" data-toc-modified-id="矩阵运算-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>矩阵运算</a></span><ul class="toc-item"><li><span><a href="#矩阵求逆" data-toc-modified-id="矩阵求逆-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>矩阵求逆</a></span></li><li><span><a href="#矩阵相乘" data-toc-modified-id="矩阵相乘-1.4.2"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>矩阵相乘</a></span></li></ul></li></ul></li><li><span><a href="#pandas" data-toc-modified-id="pandas-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>pandas</a></span></li><li><span><a href="#matplotlib" data-toc-modified-id="matplotlib-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>matplotlib</a></span></li><li><span><a href="#scikit-learn" data-toc-modified-id="scikit-learn-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>scikit-learn</a></span></li></ul></div>

## numpy

### 导入numpy库

In [3]:
import numpy as np

### numpy的两种数据结构之一：数组

In [11]:
# 创建简单的列表
a = [1, 2, 3, 4]
# 将列表转换为数组
b = np.array(a)
print("一维数组:"+str(b))

一维数组:[1 2 3 4]


In [18]:
# 生成随机的4*4数组
rand_arr = np.random.rand(4,4)
print('4*4数组：')
print(str(rand_arr))

4*4数组：
[[0.40368221 0.6609671  0.91947982 0.95247621]
 [0.99465465 0.86163295 0.90685198 0.2835494 ]
 [0.91364219 0.13310022 0.34096684 0.56975154]
 [0.35396694 0.03095031 0.52864765 0.45598583]]


### numpy的两种数据结构之二：矩阵

In [9]:
# 将数组转换为矩阵
c = np.mat(b)
print("一维矩阵:"+str(c))

一维矩阵:[[1 2 3 4]]


In [19]:
rand_mat = np.mat(rand_arr)
print('4*4矩阵：')
print(str(rand_mat))

4*4矩阵：
[[0.40368221 0.6609671  0.91947982 0.95247621]
 [0.99465465 0.86163295 0.90685198 0.2835494 ]
 [0.91364219 0.13310022 0.34096684 0.56975154]
 [0.35396694 0.03095031 0.52864765 0.45598583]]


**注意：矩阵和数组是numpy中的两种不同的数据结构，虽然看上去相似，但是执行同样函数所返回的结果不同**

### 矩阵运算

#### 矩阵求逆

In [20]:
inv_rand_mat = rand_mat.I
print("rand_mat的逆矩阵：")
print(str(inv_rand_mat))

rand_mat的逆矩阵：
[[-0.6764747   0.36168239  1.04542093 -0.11811541]
 [ 1.08644243  0.40608819  0.1064549  -2.65492783]
 [-0.67675563  0.65346016 -1.55573804  2.95116526]
 [ 1.23597968 -1.06591545  0.98489464 -0.956492  ]]


####  矩阵相乘

In [25]:
multi_mat = rand_mat*inv_rand_mat
print("矩阵与其自身的逆矩阵相乘：")
print(rand_mat)
print('乘以')
print(inv_rand_mat)
print('等于')
print(multi_mat)

矩阵与其自身的逆矩阵相乘：
[[0.40368221 0.6609671  0.91947982 0.95247621]
 [0.99465465 0.86163295 0.90685198 0.2835494 ]
 [0.91364219 0.13310022 0.34096684 0.56975154]
 [0.35396694 0.03095031 0.52864765 0.45598583]]
乘以
[[-0.6764747   0.36168239  1.04542093 -0.11811541]
 [ 1.08644243  0.40608819  0.1064549  -2.65492783]
 [-0.67675563  0.65346016 -1.55573804  2.95116526]
 [ 1.23597968 -1.06591545  0.98489464 -0.956492  ]]
等于
[[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16 -3.33066907e-16]
 [ 0.00000000e+00  1.00000000e+00 -1.11022302e-16 -1.66533454e-16]
 [ 0.00000000e+00  1.11022302e-16  1.00000000e+00 -4.44089210e-16]
 [ 0.00000000e+00  5.55111512e-17  5.55111512e-17  1.00000000e+00]]


## pandas

### 导入pandas库

In [2]:
import pandas as pd

### pandas的两种数据结构之一：Series(一维数据)

<img src="http://localhost:8888/view/notebook_ml/lessons/%E9%99%84%E5%BD%951_python%E6%95%99%E7%A8%8B/appendix_1.png"
style="width:200px;height:170px;float:left">

### pandas的两种数据结构之二：DataFrame(多维数据）

## matplotlib

## scikit-learn